### ISSUE TITLE
Have only typed attributes, some of which are identifying

### ISSUE THREAD

**Issue by roesslerj** [retest/retest-model#22]
Instead of having typed IdentifyingAttributes and untyped Attributes, we want only typed Attributes, some of which are identifying.

This resolves some other issues, such as special treatment for screenshot, text, backgroundcolor, font-family etc.

**Comment by beatngu13** [comment]
Since we somewhat use XML as the role model for our internal representation, it could make sense to look at [XSD attributes](https://www.w3schools.com/xml/schema_simple_attributes.asp) and its type system for our typed attributes, since they are quite generic.

**Comment by beatngu13** [comment]
Moved to recheck: https://github.com/retest/recheck/issues/68.
